# Generated by Django 3.2.2 on 2021-07-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPuntuacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
