# Generated by Django 3.2.2 on 2021-07-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPuntuacion', '0003_localidad_informacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidad',
            name='informacion',
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='updated',
        ),
        migrations.AddField(
            model_name='localidad',
            name='information',
            field=models.TextField(default=25),
            preserve_default=False,
        ),
    ]
