# Generated by Django 3.2.2 on 2021-07-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPuntuacion', '0004_auto_20210701_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidad',
            name='information',
        ),
        migrations.AddField(
            model_name='localidad',
            name='info',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
